{% set name = "sphinx-data-viewer" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/sphinx-data-viewer-{{ version }}.tar.gz
  sha256: f99a4bf2c09b59e2e302ff51198c62acd5df83317f0226c170e47980b4445094

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - poetry >=0.12
    - poetry-core
    - pip
  run:
    - python >=3.6.0
    - sphinx >=4.0.0
    - sphinxcontrib-jquery >=3.0.0

test:
  imports:
    - sphinx_data_viewer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/useblocks/sphinx-data-viewer
  summary: Sphinx extension to show data in an interactive list view

  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - melund
